{% set version = "0.5.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-webshot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/webshot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/webshot/webshot_{{ version }}.tar.gz
  sha256: b7c4f2be61c8c4730202a9c3604072478e30cb85b423b7497cd703cc3f49dbc0

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-callr
    - r-jsonlite
    - r-magrittr
  run:
    - r-base
    - r-callr
    - r-jsonlite
    - r-magrittr

test:
  commands:
    - $R -e "library('webshot')"           # [not win]
    - "\"%R%\" -e \"library('webshot')\""  # [win]

about:
  home: https://github.com/wch/webshot/
  license: GPL-2.0-only
  summary: Takes screenshots of web pages, including Shiny applications and R Markdown documents.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
