appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: V9M46jzIFwzXUibP/M85XMD9WmcWvfqzGedN/G3C7kNzY0Q/rgp0Rz1qL+K5FADop9iSR8tY5eVrrZHjlsk9g3GggQIGW9K3TfGXSFbFzM2nYQifkY9jWWGwplvFK0aI27eGxmuvA81XHqBDKmTz/fmZyjaN8NUtTCZxR+xUcSxC/58t0CMSnXPOensv/4kIV82plldlQmri6mz/eld/BI2w7YyoeyugjLiCNeZsOKvfv6odmErV/MjXZyVajPPaBhgJF1ErcLRB1G3eL7njxCy+MiDcH7zsyUkj5XcPhu/w1mc7zyPNLCzBjzyyMGFNNBjJnt+2ByDSHPE1LsXzNt8MWIkb36ObZVDhZMdJIQ/qU6KSM/zMLZ8DSVfaXG2xmiwXfBTY004sUwVgnZf0sIerl0zYKqSV2jE5CXyjFEDqpMN/ro+DyQz2GXoljHMR8/SxH4cDxLBj583yToxLEcg51sOugOTeWefcmufwJI5xputKVDumxgtzv1p3WacFVecAFJ+T5XtxmY1NJZzPyOQRxALRDKxx/36mDbGaMyEY6/6/QIuXAQurSCbsLPkoboKhStK17r2Y6ULhSoK3fiieJo3rfJmq+gCbEQiauh9JViOOfIYFvMejFYKgFbKli+SZEshcXxi9BqFe0d0pRlzJoh4YY1K3Bz0xORu28mE=
conda_forge_output_validation: true
